#!/usr/bin/env python3
"""
skill_lessons.py - move a lesson from the general log INTO the skill that owns it.

WHY THIS EXISTS
A lesson in cowork-lessons.md is only read by a session that decides to read
115 KB of lessons. A lesson inside the SKILL.md of the skill being used loads
whenever that skill loads. That is strictly better delivery for a trap that
only bites inside one subsystem.

WHAT IT DOES NOT CLAIM
Splicing prose into a SKILL.md is DELIVERY, not enforcement. It puts the rule
in front of a session that loads the skill; it cannot stop a session that never
loads it. Measured 2026-09-01 (digest-enforced-demotion-outruns-the-enforcer):
claiming a rule is enforced when the enforcer's scope is narrower than the
mistake is how a rule ends up nominally covered and actually blind. So this
script emits a DELIVERED block and says so in the block itself.

WHY DUPLICATION ACROSS SKILLS IS SAFE HERE
A key may route to more than one skill - a rule about writing .bat files
matters to the skill that WRITES them and the one that RUNS them. That would
normally invite drift (config-contradiction-survives-in-second-file). It does
not here, because every block is REGENERATED from the one lessons file. Hand
copies drift; generated copies cannot.

SAFETY, same contract as digest_apply.py
  - writes ONLY between the markers
  - refuses if anything outside the markers would change
  - re-reads from disk after writing, so a partial write cannot report success
  - --check exits 1 on drift and writes nothing
"""

import argparse, json, os, re, sys

START = "<!-- SKILL-LESSONS:start -->"
END   = "<!-- SKILL-LESSONS:end -->"

FIELD = lambda name: re.compile(r'^\s*-\s*\*\*' + name + r':\*\*\s*(.+?)\s*$', re.M)


def parse_lessons(path):
    txt = open(path, encoding='utf-8').read()
    entries = []
    for chunk in re.split(r'\n(?=### )', txt):
        if not chunk.startswith('### '):
            continue
        def f(name):
            m = FIELD(name).search(chunk)
            return m.group(1).strip() if m else None
        key = f('Pattern-Key')
        if not key:
            continue
        entries.append({
            'key': key,
            'title': chunk.split('\n')[0][4:].strip(),
            'rule': f('Rule'),
            'hits': f('Hits'),
            'evidence': f('Evidence'),
            'promoted': f('Promoted-to'),
        })
    return entries


def select(entries, route):
    prefixes = tuple(route.get('prefix', []))
    exact = set(route.get('exact', []))
    hit = [e for e in entries
           if e['key'] in exact or (prefixes and e['key'].startswith(prefixes))]
    # An entry with no authored Rule cannot become a one-line rule without
    # inventing one. Carry it as a bare pointer instead of paraphrasing.
    hit.sort(key=lambda e: (e['rule'] is None, e['key']))
    return hit


def render(route, rows):
    n_rule = sum(1 for r in rows if r['rule'])
    out = [START, ""]
    out.append("## Lessons already paid for \u2014 " + route['title'])
    out.append("")
    out.append(str(n_rule) + " rule(s) of " + str(len(rows)) +
               " entries routed to this skill, generated from")
    out.append("`cowork-memory/cowork-lessons.md`. **Do not hand-edit this block** \u2014 it is")
    out.append("regenerated by `skill_lessons.py` and any edit here is overwritten. Fix the")
    out.append("lesson entry instead; the Pattern-Key is the retrieval key.")
    out.append("")
    out.append("These are DELIVERED here, not enforced. A rule in this block reaches any")
    out.append("session that loads this skill; it does not reach one that never does.")
    out.append("")
    out.append("| Pattern-Key | Rule |")
    out.append("|---|---|")
    for r in rows:
        if not r['rule']:
            continue
        rule = r['rule'].replace('|', '\\|').replace('\n', ' ')
        mark = ''
        if r['hits']:
            m = re.match(r'\s*(\d+)', str(r['hits']))
            if m and int(m.group(1)) >= 2:
                mark = ' **(repeat)**'
        out.append("| `" + r['key'] + "`" + mark + " | " + rule + " |")
    unruled = [r for r in rows if not r['rule']]
    if unruled:
        out.append("")
        out.append("Also routed here, no one-line rule authored yet \u2014 read the entry before")
        out.append("working in this area: " +
                   ", ".join('`%s`' % r['key'] for r in unruled) + ".")
    out.append("")
    out.append(END)
    return "\n".join(out)


def splice(skill_md, block):
    txt = open(skill_md, encoding='utf-8').read()
    if START in txt and END in txt:
        return txt.split(START)[0] + block + txt.split(END, 1)[1], txt
    # First insertion: after the attribution notice, before the first H2.
    m = re.search(r'^## ', txt, re.M)
    if not m:
        return txt.rstrip() + "\n\n" + block + "\n", txt
    return txt[:m.start()] + block + "\n\n" + txt[m.start():], txt


def strip_block(txt):
    """The file with the generated block removed, for the byte-identity check.

    Must be comparable across the FIRST insertion too - there the old file has
    no markers at all, so a naive marker-split compares a whole file against a
    split one and always reports a difference, which would make the guard fire
    on every first write and mean nothing thereafter.
    """
    if START in txt and END in txt:
        pre = txt.split(START)[0]
        post = txt.split(END, 1)[1]
        if post.startswith("\n\n"):
            post = post[2:]
        return pre + post
    return txt


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--lessons', required=True)
    ap.add_argument('--skills-dir', required=True)
    ap.add_argument('--routes', required=True)
    ap.add_argument('--check', action='store_true', help='report only, write nothing')
    ap.add_argument('--only', help='one skill name')
    args = ap.parse_args()

    entries = parse_lessons(args.lessons)
    routes = {k: v for k, v in json.load(open(args.routes)).items()
              if not k.startswith('_')}

    print("lessons parsed: %d" % len(entries))
    print("skills routed : %d" % len(routes))
    print()

    routed_keys = set()
    changed = 0
    missing = []

    for skill in sorted(routes):
        route = routes[skill]
        if args.only and skill != args.only:
            continue
        md = os.path.join(args.skills_dir, skill, 'SKILL.md')
        if not os.path.isfile(md):
            missing.append(skill)
            print("  SKIP  %-22s no SKILL.md" % skill)
            continue

        rows = select(entries, route)
        routed_keys.update(r['key'] for r in rows)
        block = render(route, rows)
        new, old = splice(md, block)

        if strip_block(new) != strip_block(old):
            print("  FAIL  %-22s content outside the markers would change - refusing" % skill)
            return 2

        n_rule = sum(1 for r in rows if r['rule'])
        if new == old:
            print("  ok    %-22s %2d rule(s), already current" % (skill, n_rule))
        else:
            first = START not in old
            print("  %s  %-22s %2d rule(s)%s" %
                  ('NEW ' if first else 'UPD ', skill, n_rule,
                   ' (first insertion)' if first else ''))
            changed += 1
            if not args.check:
                open(md, 'w', encoding='utf-8', newline='').write(new)
                back = open(md, encoding='utf-8').read()
                if START not in back or END not in back:
                    print("  FAIL  %s: markers absent after write" % skill)
                    return 2

    print()
    unrouted = [e for e in entries if e['key'] not in routed_keys]
    print("routed to at least one skill : %d" % len(routed_keys))
    print("not routed (stay general)    : %d" % len(unrouted))
    if missing:
        print("skills in routes with no SKILL.md: " + ", ".join(missing))

    if args.check and changed:
        print("\nSTALE: %d skill(s) would change" % changed)
        return 1
    print("\n%s: %d" % ('would update' if args.check else 'updated', changed))
    return 0


if __name__ == '__main__':
    sys.exit(main())
