#!/usr/bin/env python3
"""
lesson_gate.py - make the lessons FAIL-ABLE instead of merely available.

Why this exists
---------------
`lesson_brief.py --digest` already solved retrieval: it emits every authored
Rule into copilot-instructions.md, which loads unconditionally. That is the
only delivery path measured to work.

It left two holes, both measured 2026-08-29:

  1. NOBODY CHECKS THE DIGEST IS CURRENT. The block is generated by hand and
     pasted in. Add a lesson, forget to regenerate, and the digest silently
     serves a stale rule set. Nothing complains.
  2. NOTHING FAILS. `--for <keyword>` is a lookup you may or may not perform.
     Prose that asks for an action does not get the action - that is the
     finding lesson_brief.py was itself built on, and it applies to
     lesson_brief.py.

This script closes both. It is modelled on gate_check.py from the
alteryx-to-python skill: the gate is worthless if it only advises, so every
check here can return a nonzero exit code.

Usage
-----
  preflight  Run BEFORE acting on a surface. Verifies the digest is current,
             prints the rules for that surface, and writes a receipt.
                 lesson_gate.py preflight --surface bridge \\
                     --lessons cowork-lessons.md \\
                     --instructions copilot-instructions.md

  verify     Run BEFORE a state-changing step. Asserts a receipt exists for
             this surface and this session, and that the digest has not moved
             underneath it. No receipt = nonzero exit.
                 lesson_gate.py verify --surface bridge --session <id>

  audit      Non-gating inventory: which surfaces are gate-clean, which carry
             repeat offenders that cannot travel into the digest.

Gates
-----
  G1  digest block present in the instructions file
  G2  digest counts match the lessons file (entries / rules)
  G3  digest body is byte-identical to a fresh regeneration
  G4  no repeat offender (Hits >= 2) on this surface lacks a Rule line
  G5  single-hit entries without a Rule line          -> WARN, never fails

Exit codes
----------
  0  all gates passed (G5 warnings do not affect this)
  1  a gate failed
  2  an input file could not be read
"""

import argparse
import hashlib
import io
import json
import os
import re
import sys
import tempfile
import time
from contextlib import redirect_stdout

try:
    from lesson_brief import load, rank, SURFACES
except ImportError:
    sys.stderr.write(
        "FATAL: lesson_brief.py must sit beside lesson_gate.py - this script\n"
        "       reuses its parser so the two can never disagree about what an\n"
        "       entry is.\n")
    sys.exit(2)

BEGIN = "<!-- LESSON-DIGEST:BEGIN"
END_RE = re.compile(
    r"<!-- LESSON-DIGEST:END - (\d+) always-on of (\d+) rules from "
    r"(\d+) entries -->")
KNOWN_SURFACES = [name for name, _ in SURFACES] + ["other"]


def read(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except OSError as exc:
        sys.stderr.write("FATAL: cannot read %s: %s\n" % (path, exc))
        sys.exit(2)


def regenerate(lessons_path):
    """Re-emit the digest exactly as lesson_brief --digest would."""
    from lesson_brief import cmd_digest
    entries = load(lessons_path)
    buf = io.StringIO()
    with redirect_stdout(buf):
        cmd_digest(entries, None)
    return entries, buf.getvalue()


def extract_digest(instructions_text):
    start = instructions_text.find(BEGIN)
    if start == -1:
        return None
    m = END_RE.search(instructions_text, start)
    if not m:
        return None
    return instructions_text[start:m.end()] + "\n"


def digest_fingerprint(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def default_receipt_dir():
    """Resolve a receipt directory that is actually writable.

    The documented path used to sit beside the instructions tree. In a Cowork
    session that tree is mounted READ-ONLY, so preflight printed every rule and
    then died on the receipt write - an environment fault wearing the costume
    of a rule failure (lessons-gate-receipt-dir-read-only, 2026-09-01).

    Resolution order, and the reason for each step:
      1. COWORK_RECEIPT_DIR, so a caller can pin it explicitly.
      2. .lesson-receipts under the CURRENT directory. This stays first among
         the automatic choices on purpose: the selftest runs each case in its
         own temp cwd, and a shared absolute default would let one case's
         receipt satisfy the next case's "no receipt" assertion - the sabotage
         cases would stop firing while still reporting PASS.
      3. A per-user temp directory, for the read-only-cwd case.

    preflight and verify both call this, so they cannot resolve differently.
    """
    pinned = os.environ.get("COWORK_RECEIPT_DIR")
    if pinned:
        return pinned
    if os.access(os.getcwd(), os.W_OK):
        return os.path.join(os.getcwd(), ".lesson-receipts")
    return os.path.join(tempfile.gettempdir(), "cowork-lesson-receipts")


def receipt_path(receipt_dir, session, surface):
    safe = re.sub(r"[^A-Za-z0-9_.-]", "_", "%s__%s" % (session, surface))
    return os.path.join(receipt_dir, "gate-%s.json" % safe)


def run_gates(surface, lessons_path, instructions_path):
    """Returns (failures, warnings, rules_for_surface, fingerprint)."""
    failures, warnings = [], []

    entries, fresh = regenerate(lessons_path)
    live = extract_digest(read(instructions_path))

    if live is None:
        failures.append(
            "G1 the LESSON-DIGEST block is missing from %s. Nothing loads "
            "unconditionally, so no rule is in front of you at turn 1. "
            "Regenerate with: lesson_brief.py <lessons> --digest"
            % os.path.basename(instructions_path))
        fingerprint = None
    else:
        fingerprint = digest_fingerprint(live)
        m = END_RE.search(live)
        if not m:
            # An old two-number marker lands here. Say which contract is in
            # force rather than reporting a generic staleness, or the fix
            # looks like "regenerate" when it is actually "upgrade".
            failures.append(
                "G2 the END marker does not match the tiered contract "
                "'<N> always-on of <M> rules from <K> entries'. An older "
                "two-number marker means the digest predates tiering. "
                "Regenerate with digest_apply.py.")
            claimed = None
        else:
            claimed = (int(m.group(1)), int(m.group(2)), int(m.group(3)))

        if claimed is not None:
            from lesson_brief import read_tiers, select_alwayson, DEFAULT_TIERS
            pins, enforced = read_tiers(DEFAULT_TIERS)
            actual_ruled, actual_keep = select_alwayson(entries, pins, enforced)
            actual = (len(actual_keep), len(actual_ruled), len(entries))
            if claimed != actual:
                failures.append(
                    "G2 digest is STALE: it advertises %d always-on of %d rules "
                    "from %d entries; the lessons file now holds %d always-on of "
                    "%d rules from %d entries. The difference is not loading."
                    % (claimed + actual))
            elif live.strip() != fresh.strip():
                # INDENTATION IS LOAD-BEARING HERE. When this elif was attached
                # to `if claimed is not None` instead of `if claimed != actual`,
                # G3 could only fire on an unparseable marker - that is, never
                # in normal operation. A hand-edited digest body sailed through
                # and the gate reported PASSED. Caught by
                # lesson_gate_selftest case_g3_body_edited, 2026-08-31.
                failures.append(
                    "G3 digest counts match but the body does not. A rule was "
                    "edited in the lessons file without regenerating, or the "
                    "block was hand-edited. Regenerate it.")

    on_surface = [e for e in entries if e["surface"] == surface]
    repeat_unruled = [e for e in on_surface if e["hits"] >= 2 and not e["rule"]]
    single_unruled = [e for e in on_surface if e["hits"] < 2 and not e["rule"]]

    for e in repeat_unruled:
        failures.append(
            "G4 '%s' has been hit %d times and still has no Rule line, so it "
            "cannot enter the digest and will not be loaded next session. "
            "Author one (never auto-summarise)." % (e["key"], e["hits"]))
    if single_unruled:
        warnings.append(
            "G5 %d single-hit entr(ies) on '%s' have no Rule line: %s"
            % (len(single_unruled), surface,
               ", ".join(e["key"] for e in single_unruled[:6])
               + (" ..." if len(single_unruled) > 6 else "")))

    rules = [e for e in sorted(on_surface, key=rank) if e["rule"]]
    return failures, warnings, rules, fingerprint


def report(failures, warnings):
    for w in warnings:
        print("WARN: %s" % w)
    for f in failures:
        print("FAIL: %s" % f)


def cmd_preflight(a):
    if a.surface not in KNOWN_SURFACES:
        print("FAIL: '%s' is not a known surface. Known: %s"
              % (a.surface, ", ".join(KNOWN_SURFACES)))
        return 1

    failures, warnings, rules, fingerprint = run_gates(
        a.surface, a.lessons, a.instructions)
    report(failures, warnings)

    if failures:
        print("\nGATE FAILED for surface '%s' - %d failure(s). Fix before acting."
              % (a.surface, len(failures)))
        return 1

    print("Rules in force for '%s' (%d):\n" % (a.surface, len(rules)))
    for e in rules:
        flag = " [%dx]" % e["hits"] if e["hits"] > 1 else ""
        print("  - %s%s" % (e["rule"], flag))
        print("      (%s)" % e["key"])
    if not rules:
        print("  (none authored yet)")

    # Every gate has already passed by this line, so a failure from here on is
    # the ENVIRONMENT, not the lessons. It exits 2 (could not run) and never 1
    # (stop and fix a rule) - exit 1 here would halt a close over a mount.
    try:
        os.makedirs(a.receipt_dir, exist_ok=True)
        path = receipt_path(a.receipt_dir, a.session, a.surface)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump({
                "session": a.session,
                "surface": a.surface,
                "digest_fingerprint": fingerprint,
                "rules_loaded": [e["key"] for e in rules],
                "written_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            }, fh, indent=2)
    except OSError as exc:
        print("\nGATE COULD NOT RUN - every rule above loaded and passed, but "
              "the receipt could not be written to %s: %s" % (a.receipt_dir, exc))
        print("That is an environment fault, NOT a rule failure. Point "
              "--receipt-dir (or COWORK_RECEIPT_DIR) at a writable directory "
              "and re-run. See lessons-gate-receipt-dir-read-only.")
        return 2

    print("\nGATE PASSED - receipt written to %s" % path)
    return 0


def cmd_verify(a):
    path = receipt_path(a.receipt_dir, a.session, a.surface)
    if not os.path.exists(path):
        print("FAIL: no receipt for surface '%s' in session '%s'. The lessons "
              "for this surface were never loaded. Run:\n"
              "  lesson_gate.py preflight --surface %s --session %s"
              % (a.surface, a.session, a.surface, a.session))
        return 1

    with open(path, encoding="utf-8") as fh:
        receipt = json.load(fh)

    live = extract_digest(read(a.instructions))
    current = digest_fingerprint(live) if live is not None else None
    if receipt.get("digest_fingerprint") != current:
        print("FAIL: the digest changed after the receipt was written "
              "(receipt %s, now %s). Re-run preflight - the rules you loaded "
              "are no longer the rules in force."
              % (receipt.get("digest_fingerprint"), current))
        return 1

    print("OK: surface '%s' cleared in session '%s' with %d rule(s) loaded."
          % (a.surface, a.session, len(receipt.get("rules_loaded", []))))
    return 0


def cmd_audit(a):
    entries = load(a.lessons)
    live = extract_digest(read(a.instructions))
    print("digest block: %s" % ("present" if live else "MISSING"))
    if live:
        m = END_RE.search(live)
        if m:
            print("  advertises %s always-on of %s rules from %s entries"
                  % (m.group(1), m.group(2), m.group(3)))
        else:
            # Never let a missing match crash the audit: audit is the
            # non-gating inventory and must survive a malformed input to
            # report it. m.group on None was an AttributeError here.
            print("  advertises UNPARSEABLE - the END marker does not match "
                  "the tiered contract (pre-tiering two-number marker?)")
    from lesson_brief import read_tiers, select_alwayson, DEFAULT_TIERS
    _pins, _enf = read_tiers(DEFAULT_TIERS)
    _ruled, _keep = select_alwayson(entries, _pins, _enf)
    print("  lessons file holds %d always-on of %d rules from %d entries"
          % (len(_keep), len(_ruled), len(entries)))
    print()
    print("%-10s %6s %6s %8s  %s" % ("surface", "total", "ruled", "blocked", "status"))
    for name in KNOWN_SURFACES:
        grp = [e for e in entries if e["surface"] == name]
        if not grp:
            continue
        ruled = sum(1 for e in grp if e["rule"])
        blocked = sum(1 for e in grp if e["hits"] >= 2 and not e["rule"])
        print("%-10s %6d %6d %8d  %s"
              % (name, len(grp), ruled, blocked,
                 "GATE FAILS" if blocked else "clean"))
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    sub = ap.add_subparsers(dest="cmd", required=True)

    def common(p, need_lessons=True):
        if need_lessons:
            p.add_argument("--lessons", default="cowork-lessons.md")
        p.add_argument("--instructions", default="copilot-instructions.md")
        p.add_argument("--surface", required=True)
        p.add_argument("--session", default=os.environ.get("COWORK_SESSION", "adhoc"))
        p.add_argument("--receipt-dir", default=default_receipt_dir())

    p = sub.add_parser("preflight"); common(p)
    p = sub.add_parser("verify"); common(p, need_lessons=False)
    p = sub.add_parser("audit")
    p.add_argument("--lessons", default="cowork-lessons.md")
    p.add_argument("--instructions", default="copilot-instructions.md")

    a = ap.parse_args()
    return {"preflight": cmd_preflight, "verify": cmd_verify, "audit": cmd_audit}[a.cmd](a)


if __name__ == "__main__":
    sys.exit(main())
