# ============================================================
#  Registers the Cowork bridge watchdog in Task Scheduler.
#
#  Trigger: at logon, plus every 2 minutes indefinitely.
#  Battery-proof - measured 2026-08-18, the schtasks.exe defaults
#  ("No Start On Batteries") make a task a silent no-op on this laptop
#  when it is unplugged, reporting Last Result 0 with zero output.
#
#  Idempotent: -Force replaces any existing registration.
#  Run again after editing _bridge-watchdog.ps1 only if the trigger or
#  settings changed; the script itself is read fresh on every run.
#
#  WINDOW VISIBILITY - measured 2026-08-18:
#  The original action was  powershell.exe -WindowStyle Hidden ...  and it
#  flashed a console every 2 minutes. -WindowStyle is applied by PowerShell
#  AFTER its host window already exists, so Windows draws the console first
#  and PowerShell hides it a beat later. That beat is the flash.
#  Fix: launch through conhost.exe --headless, which never creates a window
#  at all (Windows 11 / build 22000+). On older builds fall back to a
#  wscript.exe shim using Run(cmd, 0, False). Do NOT go back to
#  -WindowStyle Hidden as the launcher - it cannot suppress the flash.
# ============================================================

$ErrorActionPreference = 'Stop'

$TaskName = "CoworkBridgeWatchdog"
$Startup  = "C:\Users\YOURUSER\Documents\COPILOT_COWORK\Startup"
$Script   = Join-Path $Startup "_bridge-watchdog.ps1"
$Shim     = Join-Path $Startup "_watchdog-hidden.vbs"

if (-not (Test-Path $Script)) { throw "Watchdog script not found: $Script" }

$psArgs  = '-NoProfile -ExecutionPolicy Bypass -File "' + $Script + '"'
$build   = [int](Get-CimInstance Win32_OperatingSystem).BuildNumber
$conhost = Join-Path $env:SystemRoot "System32\conhost.exe"

if ($build -ge 22000 -and (Test-Path $conhost)) {
    $launcher = 'conhost.exe'
    $launchArgs = '--headless powershell.exe ' + $psArgs
    Write-Output ("Launcher: conhost --headless (OS build " + $build + ")")
} else {
    $vbs = @(
        '` Hidden launcher for the Cowork bridge watchdog.',
        '` Regenerated by _watchdog-install.ps1 - edit that, not this.',
        'Set sh = CreateObject("WScript.Shell")',
        'sh.Run "powershell.exe ' + ($psArgs -replace '"', '""') + '", 0, False'
    ) -join "`r`n"
    $vbs = $vbs -replace '`', "'"
    Set-Content -Path $Shim -Value $vbs -Encoding ASCII
    $launcher = 'wscript.exe'
    $launchArgs = '"' + $Shim + '"'
    Write-Output ("Launcher: wscript shim (OS build " + $build + " - conhost --headless unavailable)")
}

$action = New-ScheduledTaskAction -Execute $launcher -Argument $launchArgs

# NOTE: an -AtLogOn trigger requires ELEVATION - registering one as a standard
# user fails with "Access is denied" (HRESULT 0x80070005, measured 2026-08-18),
# and Cowork jobs cannot elevate. The repeating trigger below survives reboots
# on its own because -StartWhenAvailable re-fires a missed occurrence.

# NOTE: do NOT pass -RepetitionDuration ([TimeSpan]::MaxValue) - Task Scheduler
# rejects it outright ("P99999999DT23H59M59S ... incorrectly formatted or out of
# range", measured 2026-08-18). Omitting the duration repeats indefinitely.
$repeating = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
    -RepetitionInterval (New-TimeSpan -Minutes 2)

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit ([TimeSpan]::FromMinutes(5))

Register-ScheduledTask -TaskName $TaskName -Action $action `
    -Trigger $repeating -Settings $settings -Force | Out-Null

Write-Output "Registered scheduled task: $TaskName"

$t = Get-ScheduledTask -TaskName $TaskName
Write-Output ("State: " + $t.State)
foreach ($a in $t.Actions) { Write-Output ("Action: " + $a.Execute + " " + $a.Arguments) }
foreach ($tr in $t.Triggers) { Write-Output ("Trigger: " + $tr.CimClass.CimClassName) }

Start-ScheduledTask -TaskName $TaskName
Write-Output "Kicked off one immediate run."
exit 0
