@echo off
REM ============================================================
REM  bridge-restart-all.bat
REM  FULL RESTART. Hands off to a detached relauncher so that
REM  killing 8933 does not kill this job mid-execution.
REM
REM  WARNING: this drops all three bridges, including the one
REM  running this script. Cowork WILL lose its connection.
REM  VS Code reopens automatically via GO.bat; you must then set
REM  8931/8932/8933 to PUBLIC in the Ports panel.
REM ============================================================
REM COWORK_OUTPUT: C:\Users\YOURUSER\Documents\COPILOT_COWORK\Outputs\2026-08-17 - Bridge Repair Toolkit

setlocal
set "CW=C:\Users\YOURUSER\Documents\COPILOT_COWORK"
set "RELAUNCH=%COWORK_JOB_OUTPUT%\_relaunch-bridges.bat"

echo Writing detached relauncher: %RELAUNCH%
(
  echo @echo off
  echo REM Auto-generated by bridge-restart-all.bat. Runs detached.
  echo timeout /t 5 /nobreak ^>nul
  echo for %%%%a in ^(8931 8932 8933^) do ^(
  echo   for /f "tokens=5" %%%%p in ^('netstat -ano ^^^| findstr /R /C:":%%%%a " ^^^| findstr LISTENING'^) do taskkill /PID %%%%p /T /F ^>nul 2^>^&1
  echo ^)
  echo timeout /t 3 /nobreak ^>nul
  echo if exist "C:\Users\YOURUSER\pw-sso-profile\SingletonLock" del /f /q "C:\Users\YOURUSER\pw-sso-profile\SingletonLock" ^>nul 2^>^&1
  echo start "" "%CW%\Startup\GO.bat"
) > "%RELAUNCH%"

echo.
echo Launching relauncher detached ^(5 second delay^)...
start "cowork-relaunch" /min cmd /c "%RELAUNCH%"

echo.
echo This job now exits cleanly. In about 10-15 seconds all three
echo bridges will be killed and VS Code will be reopened by GO.bat.
echo.
echo ACTION REQUIRED AFTERWARDS:
echo   1. Wait for the three terminal panels to finish starting.
echo   2. Ports panel - set 8931, 8932, 8933 visibility to PUBLIC.
echo   3. Ask Cowork to run bridge-health.bat to confirm.
exit /b 0
